---
version: 2
jobs:
  test-automerge:
    docker:
      - image: alpine:3.8
    working_directory: /automerge
    steps:
      - checkout
      - run: python test.py

workflows:
  version: 2
  automerge:
    jobs:
      - test-automerge
